const ACCESS_TOKEN_EXP = 24 * 60 * 60; //  1 day
const REFRESH_TOKEN_EXP = 30 * 86400; // 30 days
const ACCESS_TOKEN_COOKIE_NAME = "accessToken";
const REFRESH_TOKEN_COOKIE_NAME = "refreshToken";

export {
  ACCESS_TOKEN_EXP,
  REFRESH_TOKEN_EXP,
  ACCESS_TOKEN_COOKIE_NAME,
  REFRESH_TOKEN_COOKIE_NAME,
};
